# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microtransfer?useSSL=false
    username: root
    password: password
  jpa:
    generate-ddl: true    
