# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: ${PORT:2222}   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microaccount?useSSL=false
    username: root
    password: password
  jpa:
    generate-ddl: true  
