# HTTP Srver
server:
  port: 1112
  
#Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url: /infoUser
    health-check-url-path: /healthUser 
    metadata-map:
      app-owner: aquiroz
      description: test application 
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microuser?useSSL=false
    username: root
    password: password
  jpa:
    generate-ddl: true        
      
      
