
# HTTP Server
server:
  port: 2223
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microaccount?useSSL=false
    username: root
    password: password
  jpa:
    generate-ddl: true  
